### ISSUE TITLE
Add a Java 9+ build in Travis

### ISSUE THREAD

**Issue by tsegismont** [Sammers21/vertx-cassandra-client#2]
Not a priority for now but nice to have

**Comment by Sammers21** [comment]
Yes, it would be nice to have. And I did exactly the same thing for rabbitmq-client, but when I tried to set up codecov.io support[1] I realized that `-Pcoverage` does not works on jdk9. 

[1] - https://github.com/vert-x3/vertx-rabbitmq-client/pull/64

**Comment by tsegismont** [comment]
How about deactivating code coverage testing when building on JDK9+?

2018-05-17 10:30 GMT+02:00 Pavel Drankov <notifications@github.com>:

**Comment by Sammers21** [comment]
Yes, we can detect the version on java by $JAVA_HOME variable.

**Comment by Sammers21** [comment]
@tsegismont, seems that cassandra-unit is not fine with Java 9. The build got failed for this reason.

Here also the issue in the official repository: https://github.com/jsevellec/cassandra-unit/issues/249

**Comment by tsegismont** [comment]
@Sammers21 ok let's put this one on hold then

**Comment by tsegismont** [comment]
@Sammers21 an afterthought: can we at least that it compiles with JDK9 for now? I mean, by disabling tests.

**Comment by Sammers21** [comment]
Yes, we can.
