### ISSUE TITLE
Shared client support

### ISSUE THREAD

**Issue by tsegismont** [Sammers21/vertx-cassandra-client#4]
Vert.x Mongo and JDBC clients allow to create a _shared_ client. That is, a named client.

This allows, for example, to avoid creating multiple clients if you deploy multiple instances of a verticle.

**Comment by vietj** [comment]
in practice I'm not sure this is a good idea, unless we can make sure to respect the threading model, which might be complicated if Cassandra is doing pooling on its side. So we should study this option before implementing it.

**Comment by tsegismont** [comment]
Datastax recommends to share `Cluster` and `Session` instances.
